name: pc_part_picker
description: A Flutter version of the PC Part Picker application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.1
  http: ^1.1.0
  go_router: ^12.1.0
  flutter_carousel_widget: ^2.2.0
  shared_preferences: ^2.2.2
  smooth_page_indicator: ^1.1.0
  flutter_spinkit: ^5.2.0
  animated_text_kit: ^4.2.2
  cached_network_image: ^3.3.0
  url_launcher: ^6.2.1
  flutter_svg: ^2.0.9
  intl: ^0.18.1
  shimmer: ^3.0.0
  flutter_staggered_grid_view: ^0.7.0
  scrollable_positioned_list: ^0.3.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/ 